# Generated by Django 4.2 on 2023-05-20 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(blank=True, null=True, upload_to='files/')),
                ('name', models.TextField()),
                ('extension', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_idx', models.JSONField()),
                ('col_param', models.TextField()),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.file')),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
