# Generated by Django 4.2 on 2023-06-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_file_parameter_delete_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='col_idx',
            field=models.TextField(),
        ),
    ]
