# Generated by Django 4.2 on 2023-06-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_parameter_col_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='col_idx',
            new_name='idx',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='col_param',
            new_name='limit',
        ),
        migrations.AddField(
            model_name='parameter',
            name='param',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
