# Generated by Django 4.2.2 on 2023-06-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_parameter_criteria_parameter_func'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='parameter',
            name='criteria',
            field=models.BooleanField(choices=[(False, 'Минимизация'), (True, 'Максимизация')]),
        ),
    ]
